-- New App schema (structure only, no data)
-- Generated by tools/migrate.py

CREATE TABLE IF NOT EXISTS "account_category" (
  "id" INTEGER PRIMARY KEY,
  "name" TEXT,
  "note" TEXT,
  "is_active" BOOLEAN,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "accounting_audit_log" (
  "id" TEXT,
  "module" TEXT,
  "action" TEXT,
  "entity_type" TEXT,
  "entity_id" INTEGER,
  "user_id" INTEGER,
  "username" TEXT,
  "ip_address" TEXT,
  "session_id" TEXT,
  "before_json" TEXT,
  "after_json" TEXT,
  "amount_before_minor" INTEGER,
  "amount_after_minor" INTEGER,
  "account_before_id" INTEGER,
  "account_after_id" INTEGER,
  "party_before_id" INTEGER,
  "party_after_id" INTEGER,
  "reason" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "audit_log" (
  "id" TEXT,
  "user_id" INTEGER,
  "username" TEXT,
  "action" TEXT,
  "details" TEXT,
  "timestamp" TEXT
);

CREATE TABLE IF NOT EXISTS "bill_counter" (
  "id" INTEGER PRIMARY KEY,
  "namespace" TEXT,
  "count" INTEGER
);

CREATE TABLE IF NOT EXISTS "booking_allocation_repair_archi" (
  "id" INTEGER PRIMARY KEY,
  "original_allocation_id" INTEGER,
  "sale_id" INTEGER,
  "sale_item_id" INTEGER,
  "booking_item_id" INTEGER,
  "qty" REAL,
  "was_void" BOOLEAN,
  "violations" TEXT,
  "repair_reason" TEXT,
  "repair_run_id" TEXT,
  "source_row_json" TEXT,
  "sale_snapshot_json" TEXT,
  "sale_item_snapshot_json" TEXT,
  "booking_item_snapshot_json" TEXT,
  "booking_snapshot_json" TEXT,
  "archived_at" TEXT
);

CREATE TABLE IF NOT EXISTS "cash_day_account_position" (
  "id" TEXT,
  "position_date" TEXT,
  "account_id" TEXT,
  "account_name" TEXT,
  "opening" TEXT,
  "amount_in" TEXT,
  "amount_out" TEXT,
  "transfer_in" TEXT,
  "transfer_out" TEXT,
  "expected_closing" TEXT,
  "counted" TEXT,
  "difference" TEXT,
  "is_locked" TEXT,
  "locked_by" TEXT,
  "locked_at" TEXT,
  "updated_by" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "cash_day_lock" (
  "id" TEXT,
  "lock_date" TEXT,
  "total_expected" TEXT,
  "total_counted" TEXT,
  "difference" TEXT,
  "note" TEXT,
  "locked_by" TEXT,
  "locked_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "cash_flow_category" (
  "id" INTEGER PRIMARY KEY,
  "name" TEXT,
  "direction" TEXT,
  "is_active" BOOLEAN,
  "sort_order" INTEGER,
  "notes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "cash_flow_difference_adjustment" (
  "id" INTEGER PRIMARY KEY,
  "adjustment_date" TEXT,
  "amount" INTEGER,
  "note" TEXT,
  "physical_cash_available" TEXT,
  "calculated_closing" TEXT,
  "difference" TEXT,
  "reason" TEXT,
  "old_physical_cash" TEXT,
  "edited_by" TEXT,
  "edited_date" TEXT,
  "edit_count" TEXT,
  "created_by" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "cash_flow_party" (
  "id" TEXT,
  "name" TEXT,
  "party_type" TEXT,
  "phone" TEXT,
  "note" TEXT,
  "is_active" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "client" (
  "id" INTEGER PRIMARY KEY,
  "code" TEXT,
  "name" TEXT,
  "phone" TEXT,
  "address" TEXT,
  "category" TEXT,
  "opening_balance" INTEGER,
  "opening_balance_date" TEXT,
  "is_active" BOOLEAN,
  "transferred_to_id" TEXT,
  "require_manual_invoice" BOOLEAN,
  "book_no" TEXT,
  "financial_page" TEXT,
  "cement_page" TEXT,
  "steel_page" TEXT,
  "financial_book_no" TEXT,
  "cement_book_no" TEXT,
  "steel_book_no" TEXT,
  "location_url" TEXT,
  "page_notes" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "delivery" (
  "id" TEXT,
  "client_name" TEXT,
  "manual_bill_no" TEXT,
  "auto_bill_no" TEXT,
  "photo_path" TEXT,
  "date_posted" TEXT
);

CREATE TABLE IF NOT EXISTS "delivery_person" (
  "id" INTEGER PRIMARY KEY,
  "name" TEXT,
  "phone" TEXT,
  "opening_balance" INTEGER,
  "opening_balance_date" TEXT,
  "is_active" BOOLEAN,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "direct_sale_draft" (
  "id" TEXT,
  "client_code" TEXT,
  "client_name" TEXT,
  "manual_client_name" TEXT,
  "category" TEXT,
  "driver_name" TEXT,
  "manual_bill_no" TEXT,
  "item_count" TEXT,
  "total_qty" TEXT,
  "total_amount" TEXT,
  "payload" TEXT,
  "created_by" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "fbm_cash_drawer_category" (
  "id" INTEGER PRIMARY KEY,
  "name" TEXT,
  "is_active" BOOLEAN,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "fbm_cash_drawer_entry" (
  "id" INTEGER PRIMARY KEY,
  "entry_type" TEXT,
  "amount" INTEGER,
  "category" TEXT,
  "method" TEXT,
  "note" TEXT,
  "source" TEXT,
  "date_posted" TEXT,
  "created_by" TEXT,
  "is_void" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "fbm_client" (
  "id" TEXT,
  "full_name" TEXT,
  "address" TEXT,
  "phone" TEXT,
  "identity_card" TEXT,
  "is_active" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "fbm_rental_item" (
  "id" INTEGER PRIMARY KEY,
  "name" TEXT,
  "opening_qty" INTEGER,
  "available_qty" INTEGER,
  "rent_per_day" INTEGER,
  "is_void" BOOLEAN,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "future_account_audit_log" (
  "id" TEXT,
  "message" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "invoice" (
  "id" INTEGER PRIMARY KEY,
  "client_code" TEXT,
  "client_name" TEXT,
  "invoice_no" TEXT,
  "is_manual" BOOLEAN,
  "date" TEXT,
  "total_amount" REAL,
  "balance" REAL,
  "status" TEXT,
  "is_cash" BOOLEAN,
  "created_at" TEXT,
  "created_by" TEXT,
  "is_void" BOOLEAN,
  "note" TEXT
);

CREATE TABLE IF NOT EXISTS "material_category" (
  "id" INTEGER PRIMARY KEY,
  "name" TEXT,
  "is_active" BOOLEAN,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "migration_run" (
  "id" TEXT,
  "run_key" TEXT,
  "template_type" TEXT,
  "filename" TEXT,
  "source_hash" TEXT,
  "status" TEXT,
  "mode" TEXT,
  "summary_json" TEXT,
  "uploaded_by" TEXT,
  "created_at" TEXT,
  "imported_at" TEXT
);

CREATE TABLE IF NOT EXISTS "pending_bill" (
  "id" INTEGER PRIMARY KEY,
  "client_code" TEXT,
  "client_name" TEXT,
  "bill_no" TEXT,
  "bill_kind" TEXT,
  "nimbus_no" TEXT,
  "amount" REAL,
  "reason" TEXT,
  "photo_url" TEXT,
  "photo_path" TEXT,
  "is_paid" BOOLEAN,
  "is_cash" BOOLEAN,
  "is_manual" BOOLEAN,
  "created_at" TEXT,
  "created_by" TEXT,
  "is_void" BOOLEAN,
  "note" TEXT,
  "risk_override" TEXT,
  "source_module" TEXT,
  "source_table" TEXT,
  "source_id" INTEGER,
  "source_bill_no" TEXT,
  "transaction_type" TEXT
);

CREATE TABLE IF NOT EXISTS "recon_basket" (
  "id" TEXT,
  "bill_no" TEXT,
  "inv_date" TEXT,
  "inv_client" TEXT,
  "fin_client" TEXT,
  "inv_material" TEXT,
  "inv_qty" TEXT,
  "status" TEXT,
  "match_score" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "root_backup_email_history" (
  "id" TEXT,
  "trigger_type" TEXT,
  "status" TEXT,
  "recipient_emails" TEXT,
  "subject" TEXT,
  "attachment_name" TEXT,
  "attachment_size_kb" TEXT,
  "backup_path" TEXT,
  "message" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "root_backup_settings" (
  "id" TEXT,
  "enabled" TEXT,
  "frequency" TEXT,
  "recipient_emails" TEXT,
  "include_full_raw_xlsx" TEXT,
  "include_sqlite_db" TEXT,
  "subject_prefix" TEXT,
  "keep_history_count" TEXT,
  "last_sent_at" TEXT,
  "last_status" TEXT,
  "last_message" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "root_recovery_code" (
  "id" TEXT,
  "username" TEXT,
  "code_hash" TEXT,
  "created_at" TEXT,
  "used_at" TEXT,
  "generated_by" TEXT,
  "note" TEXT
);

CREATE TABLE IF NOT EXISTS "schema_version" (
  "id" TEXT,
  "version" TEXT,
  "applied_at" TEXT
);

CREATE TABLE IF NOT EXISTS "settings" (
  "id" TEXT,
  "currency" TEXT,
  "company_name" TEXT,
  "company_address" TEXT,
  "company_phone" TEXT,
  "company_email" TEXT,
  "tax_rate" TEXT,
  "invoice_prefix" TEXT,
  "bill_prefix" TEXT,
  "ui_theme" TEXT,
  "allow_global_negative_stock" TEXT,
  "google_client_id" TEXT,
  "google_client_secret" TEXT,
  "google_refresh_token" TEXT,
  "google_access_token" TEXT,
  "google_token_expiry" TEXT,
  "google_sender_email" TEXT
);

CREATE TABLE IF NOT EXISTS "staff_email" (
  "id" TEXT,
  "email" TEXT,
  "is_active" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "supplier" (
  "id" INTEGER PRIMARY KEY,
  "name" TEXT,
  "phone" TEXT,
  "address" TEXT,
  "opening_balance" INTEGER,
  "opening_balance_date" TEXT,
  "is_active" BOOLEAN,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "system_lock" (
  "id" TEXT,
  "name" TEXT,
  "status" TEXT,
  "owner" TEXT,
  "acquired_at" TEXT,
  "ttl_seconds" TEXT,
  "note" TEXT
);

CREATE TABLE IF NOT EXISTS "user" (
  "id" INTEGER PRIMARY KEY,
  "username" TEXT,
  "password_hash" TEXT,
  "password_plain" TEXT,
  "role" TEXT,
  "status" TEXT,
  "can_view_stock" BOOLEAN,
  "can_view_daily" BOOLEAN,
  "can_view_history" BOOLEAN,
  "can_import_export" BOOLEAN,
  "can_manage_directory" BOOLEAN,
  "can_view_dashboard" BOOLEAN,
  "can_manage_grn" BOOLEAN,
  "can_manage_bookings" BOOLEAN,
  "can_manage_payments" BOOLEAN,
  "can_manage_sales" BOOLEAN,
  "can_view_delivery_rent" BOOLEAN,
  "can_manage_pending_bills" BOOLEAN,
  "can_view_reports" BOOLEAN,
  "can_manage_notifications" BOOLEAN,
  "can_view_client_ledger" BOOLEAN,
  "can_view_supplier_ledger" BOOLEAN,
  "can_view_decision_ledger" BOOLEAN,
  "can_manage_clients" BOOLEAN,
  "can_manage_suppliers" BOOLEAN,
  "can_manage_materials" BOOLEAN,
  "can_manage_delivery_persons" BOOLEAN,
  "can_access_settings" BOOLEAN,
  "can_manage_accounts" BOOLEAN,
  "can_view_cash_flow" BOOLEAN,
  "restrict_backdated_edit" BOOLEAN,
  "access_mode" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "account" (
  "id" INTEGER PRIMARY KEY,
  "name" TEXT,
  "type" TEXT,
  "category" TEXT,
  "source_category" TEXT,
  "account_type" TEXT,
  "balance" REAL,
  "balance_minor" INTEGER,
  "opening_balance" INTEGER,
  "opening_balance_minor" INTEGER,
  "opening_balance_date" TEXT,
  "bank_name" TEXT,
  "account_holder_name" TEXT,
  "account_number" TEXT,
  "branch_code" TEXT,
  "is_active" BOOLEAN,
  "revision" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT,
  "updated_by" TEXT,
  "note" TEXT,
  "class_category" TEXT,
  "class_subcategory" TEXT,
  "class_account_type" TEXT,
  "channel" TEXT,
  "cash_location" TEXT,
  "cash_responsible" TEXT,
  "wallet_provider" TEXT,
  "wallet_number" TEXT,
  "wallet_holder" TEXT,
  "linked_entity_type" TEXT,
  "linked_client_id" TEXT,
  "linked_supplier_id" TEXT,
  "linked_party_name" TEXT,
  "account_status" TEXT
);

CREATE TABLE IF NOT EXISTS "cash_flow_reconciliation_audit" (
  "id" TEXT,
  "reconciliation_id" TEXT,
  "adjustment_date" TEXT,
  "change_type" TEXT,
  "old_physical_cash" TEXT,
  "new_physical_cash" TEXT,
  "old_difference" TEXT,
  "new_difference" TEXT,
  "old_reason" TEXT,
  "new_reason" TEXT,
  "changed_by" TEXT,
  "changed_at" TEXT
);

CREATE TABLE IF NOT EXISTS "cash_flow_subcategory" (
  "id" INTEGER PRIMARY KEY,
  "category_id" INTEGER,
  "name" TEXT,
  "is_active" BOOLEAN,
  "notes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "delivery_item" (
  "id" TEXT,
  "delivery_id" TEXT,
  "product" TEXT,
  "qty" TEXT
);

CREATE TABLE IF NOT EXISTS "entry" (
  "id" INTEGER PRIMARY KEY,
  "date" TEXT,
  "time" TEXT,
  "type" TEXT,
  "material" TEXT,
  "client" TEXT,
  "client_code" TEXT,
  "client_category" TEXT,
  "qty" REAL,
  "bill_no" TEXT,
  "auto_bill_no" TEXT,
  "nimbus_no" TEXT,
  "invoice_id" TEXT,
  "created_by" TEXT,
  "created_at" TEXT,
  "is_void" BOOLEAN,
  "transaction_category" TEXT,
  "driver_name" TEXT,
  "note" TEXT,
  "booked_material" TEXT,
  "is_alternate" BOOLEAN,
  "source_module" TEXT,
  "source_table" TEXT,
  "source_id" INTEGER,
  "source_bill_no" TEXT,
  "transaction_type" TEXT
);

CREATE TABLE IF NOT EXISTS "follow_up_reminder" (
  "id" INTEGER PRIMARY KEY,
  "pending_bill_id" INTEGER,
  "remind_at" TEXT,
  "note" TEXT,
  "is_done" BOOLEAN,
  "alerted_at" TEXT,
  "acknowledged_at" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "import_upload" (
  "id" TEXT,
  "upload_id" TEXT,
  "filename" TEXT,
  "stored_filename" TEXT,
  "size_bytes" TEXT,
  "uploaded_by" TEXT,
  "uploaded_at" TEXT,
  "status" TEXT,
  "notes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "material" (
  "id" INTEGER PRIMARY KEY,
  "code" TEXT,
  "name" TEXT,
  "category_id" INTEGER,
  "unit_price" REAL,
  "total" REAL,
  "unit" TEXT,
  "is_active" BOOLEAN,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "migration_mapping" (
  "id" TEXT,
  "template_type" TEXT,
  "legacy_reference" TEXT,
  "entity_type" TEXT,
  "entity_id" TEXT,
  "run_id" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "migration_row" (
  "id" TEXT,
  "run_id" TEXT,
  "source_sheet" TEXT,
  "source_row" TEXT,
  "legacy_reference" TEXT,
  "row_hash" TEXT,
  "status" TEXT,
  "entity_type" TEXT,
  "new_entity_id" TEXT,
  "data_json" TEXT,
  "error_json" TEXT,
  "imported_at" TEXT
);

CREATE TABLE IF NOT EXISTS "plant_asset" (
  "id" TEXT,
  "asset_code" TEXT,
  "name" TEXT,
  "category" TEXT,
  "status" TEXT,
  "location" TEXT,
  "location_code" TEXT,
  "supplier_id" TEXT,
  "commissioned_on" TEXT,
  "purchase_value" TEXT,
  "purchase_value_minor" TEXT,
  "notes" TEXT,
  "is_active" TEXT,
  "idempotency_key" TEXT,
  "revision" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "account_reconciliation" (
  "id" TEXT,
  "account_id" TEXT,
  "previous_reconciliation_id" TEXT,
  "adjustment_transaction_id" TEXT,
  "reconciliation_date" TEXT,
  "period_start_at" TEXT,
  "period_end_at" TEXT,
  "previous_balance" TEXT,
  "opening_balance" TEXT,
  "transaction_in" TEXT,
  "transaction_out" TEXT,
  "transaction_net" TEXT,
  "expected_balance" TEXT,
  "actual_balance" TEXT,
  "difference" TEXT,
  "adjustment_amount" TEXT,
  "final_reconciled_balance" TEXT,
  "previous_balance_minor" TEXT,
  "opening_balance_minor" TEXT,
  "transaction_in_minor" TEXT,
  "transaction_out_minor" TEXT,
  "transaction_net_minor" TEXT,
  "expected_balance_minor" TEXT,
  "actual_balance_minor" TEXT,
  "difference_minor" TEXT,
  "final_reconciled_balance_minor" TEXT,
  "difference_type" TEXT,
  "status" TEXT,
  "note" TEXT,
  "created_by_id" TEXT,
  "created_by" TEXT,
  "created_ip" TEXT,
  "session_id" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "booking" (
  "id" INTEGER PRIMARY KEY,
  "client_name" TEXT,
  "amount" REAL,
  "paid_amount" REAL,
  "manual_bill_no" TEXT,
  "auto_bill_no" TEXT,
  "photo_path" TEXT,
  "photo_url" TEXT,
  "date_posted" TEXT,
  "is_void" BOOLEAN,
  "note" TEXT,
  "discount" REAL,
  "discount_reason" TEXT,
  "receive_in_account_id" INTEGER
);

CREATE TABLE IF NOT EXISTS "direct_sale" (
  "id" INTEGER PRIMARY KEY,
  "idempotency_key" TEXT,
  "idempotency_payload_hash" TEXT,
  "client_name" TEXT,
  "client_code" TEXT,
  "category" TEXT,
  "amount" REAL,
  "paid_amount" REAL,
  "discount" REAL,
  "discount_reason" TEXT,
  "manual_bill_no" TEXT,
  "auto_bill_no" TEXT,
  "photo_path" TEXT,
  "photo_url" TEXT,
  "invoice_id" INTEGER,
  "date_posted" TEXT,
  "is_void" BOOLEAN,
  "note" TEXT,
  "driver_name" TEXT,
  "rent_item_revenue" REAL,
  "delivery_rent_cost" REAL,
  "rent_variance_loss" REAL,
  "payment_method" TEXT,
  "payment_account_id" INTEGER,
  "bank_name" TEXT,
  "account_name" TEXT,
  "account_no" TEXT
);

CREATE TABLE IF NOT EXISTS "fbm_rental" (
  "id" TEXT,
  "client_id" TEXT,
  "item_id" TEXT,
  "qty" TEXT,
  "rent_per_unit" TEXT,
  "total_amount" TEXT,
  "qty_returned" TEXT,
  "paid_amount" TEXT,
  "discount_amount" TEXT,
  "start_datetime" TEXT,
  "return_datetime" TEXT,
  "status" TEXT,
  "payment_account_id" TEXT,
  "note" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "follow_up_contact" (
  "id" INTEGER PRIMARY KEY,
  "pending_bill_id" INTEGER,
  "reminder_id" TEXT,
  "contacted_at" TEXT,
  "channel" TEXT,
  "response" TEXT,
  "note" TEXT,
  "created_by" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "grn" (
  "id" INTEGER PRIMARY KEY,
  "supplier_id" INTEGER,
  "supplier" TEXT,
  "manual_bill_no" TEXT,
  "auto_bill_no" TEXT,
  "photo_path" TEXT,
  "photo_url" TEXT,
  "loading_cost" INTEGER,
  "freight_cost" INTEGER,
  "other_expense" INTEGER,
  "adjustment_amount" INTEGER,
  "discount" INTEGER,
  "paid_amount" INTEGER,
  "payment_type" TEXT,
  "payment_account_id" TEXT,
  "tax_percent" INTEGER,
  "tax_amount" INTEGER,
  "tax_type" TEXT,
  "bank_name" TEXT,
  "account_name" TEXT,
  "account_no" TEXT,
  "supplier_invoice_no" TEXT,
  "due_date" TEXT,
  "bill_date" TEXT,
  "date_posted" TEXT,
  "is_void" BOOLEAN,
  "note" TEXT
);

CREATE TABLE IF NOT EXISTS "import_job" (
  "id" TEXT,
  "upload_id" TEXT,
  "started_at" TEXT,
  "finished_at" TEXT,
  "status" TEXT,
  "current_sheet" TEXT,
  "current_row" TEXT,
  "total_rows" TEXT,
  "processed_rows" TEXT,
  "error_message" TEXT,
  "import_stats" TEXT,
  "initiated_by" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "payment" (
  "id" INTEGER PRIMARY KEY,
  "client_id" INTEGER,
  "client_name" TEXT,
  "amount" REAL,
  "amount_minor" INTEGER,
  "method" TEXT,
  "payment_type" TEXT,
  "source_type" TEXT,
  "source_id" INTEGER,
  "manual_bill_no" TEXT,
  "auto_bill_no" TEXT,
  "photo_path" TEXT,
  "photo_url" TEXT,
  "date_posted" TEXT,
  "is_void" BOOLEAN,
  "note" TEXT,
  "discount" REAL,
  "discount_minor" INTEGER,
  "discount_reason" TEXT,
  "bank_name" TEXT,
  "account_name" TEXT,
  "account_no" TEXT,
  "payment_account_id" INTEGER,
  "idempotency_key" TEXT,
  "idempotency_payload_hash" TEXT,
  "revision" INTEGER,
  "created_by" TEXT,
  "updated_by" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "plant_asset_movement" (
  "id" TEXT,
  "asset_id" TEXT,
  "movement_date" TEXT,
  "from_location" TEXT,
  "to_location" TEXT,
  "reason" TEXT,
  "created_by" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "supplier_payment" (
  "id" INTEGER PRIMARY KEY,
  "supplier_id" INTEGER,
  "amount" REAL,
  "amount_minor" INTEGER,
  "method" TEXT,
  "payment_type" TEXT,
  "source_type" TEXT,
  "source_id" TEXT,
  "date_posted" TEXT,
  "note" TEXT,
  "is_void" BOOLEAN,
  "bank_name" TEXT,
  "account_name" TEXT,
  "account_no" TEXT,
  "payment_account_id" INTEGER,
  "manual_bill_no" TEXT,
  "auto_bill_no" TEXT,
  "idempotency_key" TEXT,
  "idempotency_payload_hash" TEXT,
  "revision" INTEGER,
  "created_by" TEXT,
  "updated_by" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "account_transaction" (
  "id" INTEGER PRIMARY KEY,
  "from_account_id" INTEGER,
  "to_account_id" INTEGER,
  "amount" REAL,
  "amount_minor" INTEGER,
  "description" TEXT,
  "date_posted" TEXT,
  "is_void" BOOLEAN,
  "note" TEXT,
  "transaction_type" TEXT,
  "source_type" TEXT,
  "source_id" INTEGER,
  "reconciliation_id" TEXT,
  "reason" TEXT,
  "idempotency_key" TEXT,
  "created_by" TEXT,
  "voided_by" TEXT,
  "voided_at" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "booking_item" (
  "id" INTEGER PRIMARY KEY,
  "booking_id" INTEGER,
  "material_name" TEXT,
  "qty" REAL,
  "price_at_time" REAL
);

CREATE TABLE IF NOT EXISTS "delivery_rent" (
  "id" INTEGER PRIMARY KEY,
  "sale_id" INTEGER,
  "delivery_person_name" TEXT,
  "bill_no" TEXT,
  "amount" REAL,
  "note" TEXT,
  "date_posted" TEXT,
  "created_by" TEXT,
  "is_void" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "grn_item" (
  "id" INTEGER PRIMARY KEY,
  "grn_id" INTEGER,
  "mat_name" TEXT,
  "qty" INTEGER,
  "price_at_time" REAL,
  "is_void" BOOLEAN,
  "is_locked" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "import_history_entry" (
  "id" TEXT,
  "import_job_id" TEXT,
  "event_type" TEXT,
  "sheet_name" TEXT,
  "row_number" TEXT,
  "message" TEXT,
  "status_snapshot" TEXT,
  "recorded_at" TEXT,
  "created_by" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "material_return" (
  "id" INTEGER PRIMARY KEY,
  "client_name" TEXT,
  "return_type" TEXT,
  "amount" REAL,
  "manual_bill_no" TEXT,
  "auto_bill_no" TEXT,
  "date_posted" TEXT,
  "note" TEXT,
  "payment_id" INTEGER,
  "is_void" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "sale_delivery_persons" (
  "id" INTEGER PRIMARY KEY,
  "sale_id" INTEGER,
  "delivery_person_id" INTEGER,
  "bags_delivered" REAL,
  "rent_amount" REAL,
  "created_at" TEXT,
  "is_void" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "waive_off" (
  "id" INTEGER PRIMARY KEY,
  "payment_id" INTEGER,
  "client_code" TEXT,
  "client_name" TEXT,
  "bill_no" TEXT,
  "amount" REAL,
  "reason" TEXT,
  "date_posted" TEXT,
  "created_by" TEXT,
  "note" TEXT,
  "is_void" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "cash_flow_entry" (
  "id" TEXT,
  "direction" TEXT,
  "amount" TEXT,
  "amount_minor" TEXT,
  "account_id" TEXT,
  "destination_account_id" TEXT,
  "category_id" TEXT,
  "subcategory_id" TEXT,
  "party_id" TEXT,
  "party_name" TEXT,
  "party_type" TEXT,
  "description" TEXT,
  "note" TEXT,
  "reference" TEXT,
  "date_posted" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "source_type" TEXT,
  "source_id" TEXT,
  "account_tx_id" TEXT,
  "is_void" TEXT,
  "voided_at" TEXT,
  "voided_by" TEXT,
  "void_reason" TEXT,
  "idempotency_key" TEXT,
  "revision" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "delivery_person_payment" (
  "id" TEXT,
  "delivery_person_id" TEXT,
  "sale_id" TEXT,
  "allocation_id" TEXT,
  "amount_paid" TEXT,
  "amount_paid_minor" TEXT,
  "waive_off_amount" TEXT,
  "waive_off_minor" TEXT,
  "payment_account_id" TEXT,
  "method" TEXT,
  "reference" TEXT,
  "note" TEXT,
  "date_posted" TEXT,
  "idempotency_key" TEXT,
  "revision" TEXT,
  "created_by" TEXT,
  "updated_by" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "is_void" TEXT
);

CREATE TABLE IF NOT EXISTS "direct_sale_item" (
  "id" INTEGER PRIMARY KEY,
  "sale_id" INTEGER,
  "product_name" TEXT,
  "qty" REAL,
  "price_at_time" REAL,
  "grn_item_id" INTEGER,
  "cost_rate_at_sale" REAL
);

CREATE TABLE IF NOT EXISTS "material_return_item" (
  "id" INTEGER PRIMARY KEY,
  "material_return_id" INTEGER,
  "material_name" TEXT,
  "qty" REAL,
  "unit_rate" INTEGER,
  "rent_rate" INTEGER,
  "price_at_time" INTEGER
);

CREATE TABLE IF NOT EXISTS "booking_allocation" (
  "id" INTEGER PRIMARY KEY,
  "sale_id" INTEGER,
  "sale_item_id" INTEGER,
  "booking_item_id" INTEGER,
  "qty" REAL,
  "is_void" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "cash_flow_entry_audit" (
  "id" TEXT,
  "entry_id" TEXT,
  "action" TEXT,
  "before_json" TEXT,
  "after_json" TEXT,
  "reason" TEXT,
  "changed_by" TEXT,
  "changed_at" TEXT
);

CREATE TABLE IF NOT EXISTS "grn_allocation" (
  "id" INTEGER PRIMARY KEY,
  "sale_id" INTEGER,
  "sale_item_id" INTEGER,
  "grn_item_id" INTEGER,
  "qty" REAL,
  "cost_rate" REAL,
  "is_void" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "__AMS_META__" (
  "key" TEXT,
  "value" TEXT
);
